documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/*'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.properties'

enhancement:
  - head-branch: [ '^feature', 'feature' ]

fix:
  - head-branch: [ '^fix', 'fix' ]
