name: 🐛 Bug report
description: Something isn't working
title: ':bug: - <title>'
labels: ['bug', 'needs-triage']
assignees:
  - rafandoo

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug in GitWit!
        Please fill out the form below with as much detail as possible so we can reproduce and fix the issue efficiently.

  - type: input
    id: system
    attributes:
      label: Operating System
      description: Specify the operating system you're using. [Find out here](https://whatsmyos.com/)
      placeholder: e.g. macOS 14.2, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of GitWit are you running?
      placeholder: 1.0.0
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Describe the problem
      description: Describe what is happening, including the steps to reproduce the issue, the actual result, and the expected result.
      placeholder: |
        1. Go to the coffee pot.
        2. Make more coffee.
        3. Pour it into a cup.
        Expected: The cup is full of coffee.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Additional info
      description: Logs? Screenshots? Yes, please.
      placeholder: |
        - Terminal logs
        - Screenshots or screen recordings of the issue
    validations:
      required: false
