name: Setup environment
description: 'Java and Gradle ready for build'

inputs:
  java-version:
    description: 'Java version'
    required: false
    default: '21'
  distribution:
    description: 'Java distribution'
    required: false
    default: 'temurin'
  publish-scan:
    description: 'Whether to publish a build scan'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: ${{ inputs.publish-scan }}
        build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
        build-scan-terms-of-use-agree: 'yes'

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x ./gradlew
