name: Release Deployment

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: deploy-release
  cancel-in-progress: false

jobs:
  build-and-test:
    name: Build & Test Project
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set Up Build Environment
        uses: ./.github/actions/setup-env

      - name: Run Build & Tests
        run: ./gradlew clean check --no-daemon

  determine-release-type:
    name: Determine Release Type
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      is-pre-release: ${{ steps.determine.outputs.is-pre-release }}
      tag-name: ${{ github.ref_name }}

    steps:
      - name: Determine Release Type
        id: determine
        run: |
          TAG=${GITHUB_REF#refs/tags/}
            if [[ "$TAG" == *"-"* ]]; then
                echo "This is a pre-release version."
                echo "is-pre-release=true" >> $GITHUB_OUTPUT
            else
                echo "This is a stable release version."
                echo "is-pre-release=false" >> $GITHUB_OUTPUT
            fi

  package-jar:
    name: Package JAR Artifact
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set Up Build Environment
        uses: ./.github/actions/setup-env

      - name: Build JAR artifact
        run: ./gradlew runnableJar -x test --no-daemon

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v7
        with:
          name: jar-artifact
          path: build/libs/*.jar

  package-linux:
    name: Package Linux Installers
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set Up Build Environment
        uses: ./.github/actions/setup-env

      - name: Build Linux installers
        run: ./gradlew packageLinux -x test --no-daemon

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: linux-installers
          path: |
            build/packager/*.deb
            build/packager/*.rpm

  package-windows:
    name: Package Windows Installer
    runs-on: windows-latest
    needs: build-and-test
    permissions:
      contents: read

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Set Up Build Environment
        uses: ./.github/actions/setup-env

      - name: Install Inno Setup
        run: choco install -y innosetup

      - name: Build Windows installer
        run: ./gradlew packageWindows -x test --no-daemon

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-installer
          path: build/packager/*.exe

  build-docs:
    name: Build Documentation Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Up Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Documentation Dependencies
        run: bun install
        working-directory: ./src/main/docs

      - name: Build VitePress Documentation
        run: |
          bun run docs:build
          touch .vitepress/dist/.nojekyll
        working-directory: ./src/main/docs

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./src/main/docs/.vitepress/dist

  deploy-docs:
    name: Deploy to GitHub Pages
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Artifacts to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    name: Publish Release Artifacts
    runs-on: ubuntu-latest
    needs: [ determine-release-type, package-jar, package-linux, package-windows ]
    permissions:
      contents: write

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v8
        with:
          name: jar-artifact
          path: dist/jar

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v8
        with:
          name: linux-installers
          path: dist/linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v8
        with:
          name: windows-installer
          path: dist/windows

      - name: Verify Release Artifacts
        run: ls -R dist

      - name: Generate SHA256 files
        run: |
          cd dist

          find . -type f ! -name "*.sha256" | while read -r file; do
            filename=$(basename "$file")
            hash=$(sha256sum "$file" | awk '{print $1}')
            echo "$hash  $filename" > "$file.sha256"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.determine-release-type.outputs.tag-name }}
          name: ${{ needs.determine-release-type.outputs.tag-name }}
          draft: false
          prerelease: ${{ needs.determine-release-type.outputs.is-pre-release }}
          body: |
            **${{ needs.determine-release-type.outputs.tag-name }}**
          files: |
            dist/jar/**
            dist/linux/**
            dist/windows/**
